routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/**
 * Auth routes
 */
Route::group(['namespace' => 'Auth'], function () {

    // Authentication Routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::get('logout', 'LoginController@logout')->name('logout');

    // Registration Routes...
    if (config('auth.users.registration')) {
        Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
        Route::post('register', 'RegisterController@register');
    }

    // Password Reset Routes...
    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset');

    // Confirmation Routes...
    if (config('auth.users.confirm_email')) {
        Route::get('confirm/{user_by_code}', 'ConfirmController@confirm')->name('confirm');
        Route::get('confirm/resend/{user_by_email}', 'ConfirmController@sendEmail')->name('confirm.send');
    }

    // Social Authentication Routes...
    Route::get('social/redirect/{provider}', 'SocialLoginController@redirect')->name('social.redirect');
    Route::get('social/login/{provider}', 'SocialLoginController@login')->name('social.login');
});

/**
 * Backend routes
 */
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {

    // Dashboard
    Route::get('/', 'DashboardController@index')->name('dashboard');

    //Users
    Route::get('users', 'UserController@index')->name('users');
    Route::get('users/{user}', 'UserController@show')->name('users.show');
    Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit');
    Route::put('users/{user}', 'UserController@update')->name('users.update');
    Route::delete('users/{user}', 'UserController@destroy')->name('users.destroy');
    Route::get('permissions', 'PermissionController@index')->name('permissions');
    Route::get('permissions/{user}/repeat', 'PermissionController@repeat')->name('permissions.repeat');
    Route::get('dashboard/log-chart', 'DashboardController@getLogChartData')->name('dashboard.log.chart');
    Route::get('dashboard/registration-chart', 'DashboardController@getRegistrationChartData')->name('dashboard.registration.chart');
});


Route::get('/', 'HomeController@index');

/**
 * Membership
 */
Route::group(['as' => 'protection.'], function () {
    Route::get('membership', 'MembershipController@index')->name('membership')->middleware('protection:' . config('protection.membership.product_module_number') . ',protection.membership.failed');
    Route::get('membership/access-denied', 'MembershipController@failed')->name('membership.failed');
    Route::get('membership/clear-cache/', 'MembershipController@clearValidationCache')->name('membership.clear_validation_cache');
});

Route::middleware('auth')->group(function () {

    // Dashboard
    Route::get('dashboard', 'DashboardController@index')->name('new_dashboard');

    Route::namespace('Financeiro')->group(function () {
    // Controllers Within The "App\Http\Controllers\Financeiro" Namespace

        Route::prefix('financeiro')->group(function () {

            Route::get('/', 'SaidaController@index')->name('financeiro_saida');
            Route::get('cadastrar', 'SaidaController@create');
            Route::post('cadastrar', 'SaidaController@store');
            Route::get('editar/{id}', 'SaidaController@edit');
            Route::post('editar/{id}', 'SaidaController@update');
            Route::post('excluir/{id}', 'SaidaController@destroy');
            Route::get('dividir_conta', 'SaidaController@dividir_conta');
            Route::get('dividir_conta_igualmente', 'SaidaController@dividir_conta_igualmente');
            Route::get('input_individual', 'SaidaController@input_individual');
        });

        Route::prefix('entrada')->group(function () {

            Route::get('/', 'EntradaController@index')->name('financeiro_entrada');
            Route::get('cadastrar', 'EntradaController@create');
            Route::post('cadastrar', 'EntradaController@store');
            Route::get('editar/{id}', 'EntradaController@edit');
            Route::post('editar/{id}', 'EntradaController@update');
            Route::post('excluir/{id}', 'EntradaController@destroy');
        });

        Route::prefix('formapagamento')->group(function () {

            Route::get('/', 'FormaPagamentoController@index');
            Route::get('cadastrar', 'FormaPagamentoController@create');
            Route::post('cadastrar', 'FormaPagamentoController@store');
            Route::get('editar/{id}', 'FormaPagamentoController@edit');
            Route::post('editar/{id}', 'FormaPagamentoController@update');
            Route::post('excluir/{id}', 'FormaPagamentoController@destroy');
        });

        Route::prefix('historico')->group(function () {

            Route::get('/', 'HistoricoController@index');
            Route::get('ajax', 'HistoricoController@ajax');
            // Route::get('cadastrar', 'HistoricoController@create');
            // Route::post('cadastrar', 'HistoricoController@store');
            // Route::get('editar/{id}', 'HistoricoController@edit');
            // Route::post('editar/{id}', 'HistoricoController@update');
            // Route::post('excluir/{id}', 'HistoricoController@destroy');
        });


    });
});

resources/views/layouts/sections/footer.blade.php
<div class="pull-right">
    &copy; {{ date('Y') }} {{ config('app.name') }}. {{ __('views.backend.section.footer.copyright') }}
</div>
<div class="clearfix"></div>

resources/views/layouts/sections/header.blade.php
<div class="top_nav">
    <div class="nav_menu">
        <nav>
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown"
                       aria-expanded="false">
                        <img src="{{ auth()->user()->avatar }}" alt="">{{ auth()->user()->name }}
                        <span class=" fa fa-angle-down"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                        <li>
                            <a href="{{ route('logout') }}">
                                <i class="fa fa-sign-out pull-right"></i> {{ __('views.backend.section.header.menu_0') }}
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</div>

resources/views/layouts/sections/navigation.blade.php
<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
            <a href="{{ route('admin.dashboard') }}" class="site_title">
                <span>{{ config('app.name') }}</span>
            </a>
        </div>

        <div class="clearfix"></div>

        <!-- menu profile quick info -->
        <div class="profile clearfix">
            <div class="profile_pic">
                <img src="{{ auth()->user()->avatar }}" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
                <h2>{{ auth()->user()->name }}</h2>
            </div>
        </div>
        <!-- /menu profile quick info -->

        <br/>

        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
                <h3>Financeiro</h3>
                <ul class="nav side-menu">
                    <li>
                        <a href="{{ route('new_dashboard') }}">
                            <i class="fa fa-home" aria-hidden="true"></i>
                            Dashboard
                        </a>
                    </li>
                    <li>
                        <a href="{{ route('financeiro_saida') }}">
                            <i class="fa fa-arrow-up" aria-hidden="true" style="color: red"></i>
                            Saída de Caixa
                        </a>
                    </li>
                    <li>
                        <a href="{{ route('financeiro_entrada') }}">
                            <i class="fa fa-arrow-down" aria-hidden="true" style="color: green"></i>
                            Entrada de Caixa
                        </a>
                    </li>
                </ul>
            </div>

            <div class="menu_section">
                <h3>Configurações</h3>
                <ul class="nav side-menu">
                    <li>
                        <a href="{{ url('/formapagamento') }}">
                            <i class="fa fa-money" aria-hidden="true"></i>
                            Forma de Pagamento
                        </a>
                    </li>
                </ul>
            </div>

            <div class="menu_section">
                <h3>Histórico</h3>
                <ul class="nav side-menu">
                    <li>
                        <a href="{{ url('/historico') }}">
                            <i class="fa fa-history" aria-hidden="true"></i>
                            Relatório
                        </a>
                    </li>
                </ul>
            </div>

            @if (auth()->user()->isAdmin())
            <div class="menu_section">
                <h3>{{ __('views.backend.section.navigation.sub_header_1') }}</h3>
                <ul class="nav side-menu">
                    <li>
                        <a href="{{ route('admin.users') }}">
                            <i class="fa fa-users" aria-hidden="true"></i>
                            {{ __('views.backend.section.navigation.menu_1_1') }}
                        </a>
                    </li>
                    <li>
                        <a href="{{ route('admin.permissions') }}">
                            <i class="fa fa-key" aria-hidden="true"></i>
                            {{ __('views.backend.section.navigation.menu_1_2') }}
                        </a>
                    </li>
                </ul>
            </div>
            

            <div class="menu_section">
                <h3>{{ __('views.backend.section.navigation.sub_header_2') }}</h3>

                <ul class="nav side-menu">
                    <li>
                        <a>
                            <i class="fa fa-list"></i>
                            {{ __('views.backend.section.navigation.menu_2_1') }}
                            <span class="fa fa-chevron-down"></span>
                        </a>
                        <ul class="nav child_menu">
                            <li>
                                <a href="{{ route('log-viewer::dashboard') }}">
                                    {{ __('views.backend.section.navigation.menu_2_2') }}
                                </a>
                            </li>
                            <li>
                                <a href="{{ route('log-viewer::logs.list') }}">
                                    {{ __('views.backend.section.navigation.menu_2_3') }}
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="menu_section">
                <h3>{{ __('views.backend.section.navigation.sub_header_3') }}</h3>
                <ul class="nav side-menu">
                  <li>
                      <a href="http://netlicensing.io/?utm_source=Laravel_Boilerplate&utm_medium=github&utm_campaign=laravel_boilerplate&utm_content=credits" target="_blank" title="Online Software License Management"><i class="fa fa-lock" aria-hidden="true"></i>NetLicensing</a>
                  </li>
                  <li>
                      <a href="https://photolancer.zone/?utm_source=Laravel_Boilerplate&utm_medium=github&utm_campaign=laravel_boilerplate&utm_content=credits" target="_blank" title="Individual digital content for your next campaign"><i class="fa fa-camera-retro" aria-hidden="true"></i>Photolancer Zone</a>
                  </li>
                </ul>
            </div>
            @endif
        </div>
        <!-- /sidebar menu -->
    </div>
</div>